### ISSUE TITLE
 teresa_common

### ISSUE THREAD

**Issue by Sui-he-ru-hai** [robotics-upo/upo_robot_navigation#5]
Hello sir,
I have 2 questions to ask you,
1: I got the following error when running the upo_navigation.launch file of elderly_center under upo_launchers, ERROR: cannot launch node of type [laser_assembler/laser_assembler]: can't locate node [laser_assembler] in package [laser_assembler], but laser_assembler It has been installed, and the environment variables are no problem.
2: When running some other launch files, it is found that there is no teresa_common package.
Do you know the answers to these 2 questions?
  Thank you!

**Comment by noeperez** [comment]
Hello,

I'm very sorry, these packages are not longer supported. 
They have some old dependencies to packages used in the project TERESA that should have been removed.
For instance, laser_assembler is not the common ros package. It was a different package that we programmed to fusion two sensor sources, so probably it has different parameters and node name than the public ros package. 
And teresa_common was also a package of the TERESA project with messages definitions and general configuration parameters that is not available anymore. 
Only some of the packages of the upo_robot_navigation can be used after removing all the unnecessary dependencies. Sorry for the inconvenience.
